#!/usr/bin/env bash
# tools/deploy/deploy.sh — pull the repo, install deps, link the systemd
# unit + udev rules into place on a Pi 3 B+ runtime.
#
# Run AFTER tools/deploy/bootstrap.sh (needs the pipettebot user + dirs it
# creates). Idempotent: re-running after a partial failure re-clones or
# fast-forwards the checkout and re-links the same paths — no assumption
# this is the first run.
#
# Usage:
#   sudo tools/deploy/deploy.sh [--dry-run]
#
# --dry-run prints every action that would be taken (prefixed `+`) without
# executing it — no git, no pip, no ln/systemctl/udevadm. Safe to run
# without root, sudo, git, or systemd/udev installed. It verifies the PLAN
# only; the commands it prints still need a real Pi to execute correctly.
#
# Deliberately does NOT enable or start orchestrator.service: this repo
# drives physical motion (gantry + pipette), and docs/sbc-deployment.md's
# existing guidance is that auto-start-on-boot stays opt-in until safety
# interlocks land (issue #11). The operator activates it explicitly after
# this script finishes — see the final log line.

set -euo pipefail

REPO_URL="${PIPETTEBOT_REPO_URL:-https://github.com/qte77/i3mega-pipettebot.git}"
SERVICE_USER="${PIPETTEBOT_USER:-pipettebot}"
INSTALL_DIR="${PIPETTEBOT_INSTALL_DIR:-/opt/pipettebot}"
CONFIG_DIR="${PIPETTEBOT_CONFIG_DIR:-/etc/pipettebot}"
UNIT_NAME="orchestrator.service"
UDEV_RULES_NAME="99-pipettebot.rules"
SYSTEMD_DIR="${PIPETTEBOT_SYSTEMD_DIR:-/etc/systemd/system}"
UDEV_RULES_DIR="${PIPETTEBOT_UDEV_RULES_DIR:-/etc/udev/rules.d}"

DRY_RUN=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        *)
            echo "deploy.sh: unknown argument: $arg (only --dry-run is supported)" >&2
            exit 1
            ;;
    esac
done

log() { echo "[deploy] $*"; }

run() {
    log "+ $*"
    if [ "$DRY_RUN" -eq 0 ]; then
        "$@"
    fi
}

log "target: repo=$REPO_URL install_dir=$INSTALL_DIR user=$SERVICE_USER dry_run=$DRY_RUN"

# 1. pull repo (idempotent: clone if missing, else fetch + hard-reset to latest main)
if [ -d "$INSTALL_DIR/.git" ]; then
    run sudo -u "$SERVICE_USER" git -C "$INSTALL_DIR" fetch origin main
    run sudo -u "$SERVICE_USER" git -C "$INSTALL_DIR" reset --hard origin/main
else
    run sudo -u "$SERVICE_USER" git clone "$REPO_URL" "$INSTALL_DIR"
fi

# 2. install deps as the service user: plain venv + pip, not uv. uv is
#    great for an interactive dev bring-up (tools/setup_pi.sh) run as
#    whoever is logged in, but here it would need to be resolved and
#    executed as `pipettebot` over `sudo -u` — sudo's secure_path strips a
#    per-user `~/.local/bin`, and an operator's own uv install typically
#    isn't even readable by another account's 700 $HOME. python3-venv +
#    pip (installed by bootstrap.sh) sidesteps all of that and is
#    idempotent to rerun.
run sudo -u "$SERVICE_USER" bash -c \
    "cd '$INSTALL_DIR' && python3 -m venv .venv && .venv/bin/pip install --upgrade pip && .venv/bin/pip install -e ."

# 3. symlink the systemd unit + udev rules from the checkout into place
#    (idempotent: ln -sf replaces any existing symlink at the same path)
run sudo ln -sf "$INSTALL_DIR/tools/deploy/$UNIT_NAME" "$SYSTEMD_DIR/$UNIT_NAME"
run sudo ln -sf "$INSTALL_DIR/tools/deploy/$UDEV_RULES_NAME" "$UDEV_RULES_DIR/$UDEV_RULES_NAME"
run sudo systemctl daemon-reload
run sudo udevadm control --reload-rules
run sudo udevadm trigger

# 4. seed a starter env file for orchestrator.service's `EnvironmentFile=`
#    (idempotent: never overwrites an existing one — a re-deploy must not
#    clobber an operator's PRINTER_PORT/PIPETTE_PORT/SO101_CONFIG choices).
#    Without this file the unit still starts, but the row-tour script's
#    DRY RUN mode (no PRINTER_PORT/PIPETTE_PORT set) silently does nothing —
#    see examples/showcase_v0_i3_full_pipettebot_rows.py's "Run modes".
ENV_FILE="$CONFIG_DIR/orchestrator.env"
if [ -f "$ENV_FILE" ]; then
    log "config already present, leaving as-is: $ENV_FILE"
else
    TMP_ENV="$(mktemp)"
    cat > "$TMP_ENV" <<'EOF'
# Generated by tools/deploy/deploy.sh — KEY=VALUE, no "export" (systemd
# EnvironmentFile syntax). /dev/i3mega and /dev/dpette come from
# tools/deploy/99-pipettebot.rules; edit if your udev rule uses different
# names, or add NUM_CYCLES / MOTION_PROFILE / SO101_CONFIG / etc. — see
# examples/showcase_v0_i3_full_pipettebot_rows.py's docstring for the full
# list of env vars orchestrator.service reads.
PRINTER_PORT=/dev/i3mega
PIPETTE_PORT=/dev/dpette
EOF
    run sudo install -o "$SERVICE_USER" -g "$SERVICE_USER" -m 0640 "$TMP_ENV" "$ENV_FILE"
    rm -f "$TMP_ENV"
fi

log "deploy complete. orchestrator.service is installed but NOT enabled/started"
log "(physical motion — operator opts in explicitly):"
log "  sudo systemctl start orchestrator.service    # one-off manual run"
log "  sudo systemctl enable orchestrator.service   # boot-time autostart"
