"""Hardware-motion: tip pickup from the tip-box, then mechanical ejection at the release bar.

End-to-end mechanical cycle, no dPette command traffic — the tip is
*ejected* by hooking the dPette handle onto a fixed bar above the
deck. The hook on top of the handle approaches the bar from above,
drops down into engagement, and then the gantry lifts: the bar holds
the handle in place while the body keeps rising, so the handle moves
down relative to the body and pops the tip off.

Sequence (mirrors the hand-traced G-code that calibrated the geometry):

    G28
    G1 Z90              ; safe raise after home
    G1 X170 Y152        ; over tip-box pickup slot
    G1 Z59              ; press dPette cones into tips
    G1 Z119             ; min clearance over tip-box AND bar above

    G1 X45              ; lateral park — clear of bar before going up
    G1 Z170             ; raise above the bar for cross-deck traverse
    G1 X70 Y212         ; over release station — hook now above the bar
    G1 Z145             ; descend — hook drops into engagement from above
    G1 Z170             ; raise — bar holds the handle, body rises, handle
                        ;          descends relative to body → tip ejected
    G1 X45              ; retract sideways to free the hook
    G28

Required environment variable:

    PRINTER_PORT   Marlin USB-serial path. Run `tools/preflight.py` first.

Optional:

    PRINTER_BAUD     Default 250000 (Anycubic stock + MARLIN-AI3M).
    OUTPUT_GCODE    Path to also tee the G-code stream to disk.
                    Default: `showcase_v0_tip_pickup_release.gcode` in the cwd.
                    Set to empty (`OUTPUT_GCODE=`) to disable.

**Safety**: the printer descends to Z=59 at (X=170, Y=152) — the
tip-box slot — and traverses through Z=170 at (X=70, Y=212) — the
release-bar station. Both locations must be clear of anything except
the calibrated tip-box and bar fixture. v0 has no soft-limit
enforcement (see `.claude/rules/motion-safety.md`).
"""

from __future__ import annotations

import os
import sys
import time
from typing import TYPE_CHECKING

from pipettebot.gantry import open_marlin_port
from pipettebot.motion_profile import select_profile

if TYPE_CHECKING:
    from typing import TextIO

    import serial  # type: ignore[import-untyped]

DEFAULT_BAUD = 250000
DEFAULT_GCODE_OUT = "showcase_v0_tip_pickup_release.gcode"

# Deck geometry (i3 Mega bed: 210 x 210 mm).
# Every coordinate below names the deck slot it represents — per
# `.claude/rules/motion-safety.md`, untrusted coordinates in v0.

POST_HOME_TRAVEL_Z = 90.0  # safe Z after G28, clear of all fixtures
TIP_BOX_X = 170.0  # tip-box pickup column (back-right corner)
TIP_BOX_Y = 152.0  # tip-box pickup row
TIP_PICKUP_Z = 59.0  # dPette cones pressed into tips
TIP_BOX_CLEAR_Z = 119.0  # min clearance: above tip-box top, below release bar
LATERAL_PARK_X = 45.0  # X clear of the release-bar footprint
PEAK_Z = 170.0  # above the release bar (cross-deck traverse altitude)
RELEASE_X = 70.0  # under the release bar
RELEASE_Y = 212.0  # under the release bar (back of bed)
BAR_ENGAGE_Z = 145.0  # hook dropped into engagement from above the bar

# Feedrates (under M203 X500 Y500 / Z20 caps after the M203 bump below).
XY_FEED = 6000  # 100 mm/s
Z_FEED = 1200  # 20 mm/s — needs M203 Z20 sent first


def gsend(
    link: serial.Serial,
    cmd: str,
    *,
    gcode_out: TextIO | None = None,
    max_secs: float = 180.0,
) -> None:
    """Send `cmd` to Marlin and (optionally) tee it into `gcode_out`.

    Tolerates intermediate `echo:busy: processing` lines (long G28 / M400)
    and the SD-init chatter Marlin emits when the card is unreadable.
    Raises on hard protocol/motion errors.
    """
    print(f"  >>> {cmd}")
    if gcode_out is not None:
        gcode_out.write(cmd + "\n")
    link.write((cmd + "\n").encode("ascii"))
    deadline = time.time() + max_secs
    while time.time() < deadline:
        raw = link.readline()
        if not raw:
            continue
        s = raw.decode("ascii", errors="replace").rstrip()
        if not s:
            continue
        if s == "ok" or s.startswith("ok "):
            return
        if "volume.init" in s or "SD init" in s:
            continue  # benign — card unreadable, motion unaffected
        if s.startswith(("Resend:", "!! ", "Error:Printer halted", "Error:Thermal")):
            raise RuntimeError(f"Marlin error: {s} (after `{cmd}`)")
    raise TimeoutError(f"no `ok` after {max_secs}s for `{cmd}`")


def _gcode_header() -> str:
    return (
        "; showcase_v0_tip_pickup_release.gcode\n"
        "; generated by examples/showcase_v0_tip_pickup_release.py\n"
        "; tested against Anycubic i3 Mega + MARLIN-AI3M v1.4.6\n"
        "; tip ejection is mechanical — bar catches the dPette handle hook;\n"
        "; no dPette serial commands are sent.\n"
    )


def _pickup(link: serial.Serial, gcode_out: TextIO | None) -> None:
    """Approach tip-box, press cones into tips, lift to bar-safe clearance."""
    print("[host] === PICKUP @ tip-box ===")
    if gcode_out is not None:
        gcode_out.write("\n; ===== PICKUP @ tip-box =====\n")
    gsend(link, f"G1 Z{POST_HOME_TRAVEL_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)
    gsend(link, f"G1 X{TIP_BOX_X:.3f} Y{TIP_BOX_Y:.3f} F{XY_FEED}", gcode_out=gcode_out)
    gsend(link, "M400", gcode_out=gcode_out)
    gsend(link, f"G1 Z{TIP_PICKUP_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)
    gsend(link, f"G1 Z{TIP_BOX_CLEAR_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)
    gsend(link, "M400", gcode_out=gcode_out)


def _release(link: serial.Serial, gcode_out: TextIO | None) -> None:
    """Cross to release station, drop hook into bar from above, lift to eject."""
    print("[host] === RELEASE @ ejection bar ===")
    if gcode_out is not None:
        gcode_out.write(
            "\n; ===== RELEASE @ ejection bar =====\n"
            "; approach from above the bar (Z170), drop the handle hook into\n"
            "; engagement (Z145), then lift (Z170): the bar holds the handle,\n"
            "; the body keeps rising → handle moves down relative to body → eject.\n"
        )
    gsend(link, f"G1 X{LATERAL_PARK_X:.3f} F{XY_FEED}", gcode_out=gcode_out)
    gsend(link, f"G1 Z{PEAK_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)
    gsend(link, f"G1 X{RELEASE_X:.3f} Y{RELEASE_Y:.3f} F{XY_FEED}", gcode_out=gcode_out)
    gsend(link, "M400", gcode_out=gcode_out)
    gsend(link, f"G1 Z{BAR_ENGAGE_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)  # hook in
    gsend(link, f"G1 Z{PEAK_Z:.3f} F{Z_FEED}", gcode_out=gcode_out)  # eject stroke
    gsend(link, "M400", gcode_out=gcode_out)
    gsend(link, f"G1 X{LATERAL_PARK_X:.3f} F{XY_FEED}", gcode_out=gcode_out)
    gsend(link, "M400", gcode_out=gcode_out)


def _run(link: serial.Serial, gcode_out: TextIO | None) -> None:
    if gcode_out is not None:
        gcode_out.write(_gcode_header())
    profile = select_profile(os.environ.get("MOTION_PROFILE"))
    if profile is None:
        print("[host] motion profile: SKIPPED (MOTION_PROFILE opt-out)")
        if gcode_out is not None:
            gcode_out.write("; motion profile: SKIPPED (MOTION_PROFILE opt-out)\n")
    else:
        print(f"[host] motion profile: {profile.name}")
        if gcode_out is not None:
            gcode_out.write(
                f"; motion profile: {profile.name} "
                "(via pipettebot.motion_profile.select_profile)\n"
            )
        for cmd in profile.as_marlin():
            gsend(link, cmd, gcode_out=gcode_out)

    if gcode_out is not None:
        gcode_out.write("\n; ===== initial home =====\n")
    gsend(link, "G28", gcode_out=gcode_out, max_secs=120)
    gsend(link, "M400", gcode_out=gcode_out)

    _pickup(link, gcode_out)
    _release(link, gcode_out)

    if gcode_out is not None:
        gcode_out.write("\n; ===== final home =====\n")
    gsend(link, "G28", gcode_out=gcode_out, max_secs=120)
    gsend(link, "M400", gcode_out=gcode_out)


def main() -> int:
    port = os.environ.get("PRINTER_PORT")
    if not port:
        sys.stderr.write(
            "ERROR: set PRINTER_PORT to your printer's serial port.\n"
            "       Run `uv run tools/preflight.py` to discover it.\n"
        )
        return 1
    baud = int(os.environ.get("PRINTER_BAUD", str(DEFAULT_BAUD)))
    gcode_path = os.environ.get("OUTPUT_GCODE", DEFAULT_GCODE_OUT)

    link = open_marlin_port(port, baudrate=baud, timeout=2.0)
    if link is None:
        sys.stderr.write(
            f"ERROR: could not open {port} @ {baud} baud.\n"
            "       Run `uv run tools/preflight.py` to verify the port.\n"
        )
        return 1
    with link:
        print(f"[host] open {port} @ {baud}; waiting 3s for Marlin boot")
        time.sleep(3)
        link.reset_input_buffer()
        if gcode_path:
            print(f"[host] tee G-code stream to {gcode_path}")
            with open(gcode_path, "w") as gf:
                _run(link, gf)
        else:
            _run(link, None)
        print("[host] done — tip picked up and ejected, gantry at home")
    return 0


if __name__ == "__main__":
    sys.exit(main())
